"""
Pre-render the offline demo: broadcast video on the LEFT, a live commentary feed
generated by the Transformer on the RIGHT, appearing at each event's real timestamp.

Rendered ahead of time so nothing can fail during the presentation - the output is a
plain .mp4 that plays anywhere with no Python, no GPU and no internet.

    python demo_render.py                      # default window around the goal
    python demo_render.py --start 1710 --end 1960
    python demo_render.py --out outputs/other.mp4

Default: Manchester United 1 - 1 Arsenal (official TEST split), first half,
28:30 - 32:40, which contains 5 annotated events including Ander Herrera's goal
at 29:51.

Does NOT touch the model or the training pipeline. Inference only.
"""

import argparse
import json
import re
import sys
from pathlib import Path

import cv2
import torch

from generate import build_banned_mask, load_model, restore_names
from train import CommentaryDataset, collate

ROOT = Path(__file__).resolve().parent
VIDEO = (ROOT / "data" / "caption-2024" / "england_epl" / "2014-2015" /
         "2015-05-17 - 18-00 Manchester United 1 - 1 Arsenal" / "1_224p.mkv")
CKPT = ROOT / "checkpoints" / "full_best.pt"
DATA = ROOT / "data" / "processed.json"
REF_IDX = 84                      # the Herrera goal; also identifies the game

# ---- layout -------------------------------------------------------------
VID_W, VID_H = 720, 405           # 398x224 upscaled, same 1.777 aspect
INFO_H = 215                      # panel under the video
FEED_W = 560                      # commentary feed on the right
W, H = VID_W + FEED_W, VID_H + INFO_H

FONT = cv2.FONT_HERSHEY_SIMPLEX
BG = (18, 21, 26)
WHITE, GREY, GREEN, BLUE, AMBER, GOLD = (
    (235, 235, 235), (145, 145, 145), (140, 220, 150),
    (240, 180, 110), (100, 200, 250), (90, 200, 255),
)

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def secs(game_time):
    m = re.match(r"(\d+) - (\d+):(\d+)", game_time)
    return int(m.group(2)) * 60 + int(m.group(3)) if m else None


def wrap(text, max_chars):
    lines, cur = [], ""
    for word in text.split():
        if len(cur) + len(word) + 1 <= max_chars:
            cur = f"{cur} {word}".strip()
        else:
            lines.append(cur)
            cur = word
    if cur:
        lines.append(cur)
    return lines


@torch.no_grad()
def generate_events(start_s, end_s, labelled_only=False, dedupe_label=False):
    """Annotated events in the window, with model-generated commentary.

    labelled_only: drop <no_event> rows. They carry almost no conditioning signal
    (half, minute, teams, one player) and the model mode-collapses on them - four
    consecutive ones all generate "is adjudged offside" regardless of the reference.
    See CLAUDE.md 4.15. Keeping them would make the feed repetitive and wrong.
    dedupe_label: at most one event per label, so the feed shows variety.
    """
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model, vocab, ck = load_model(str(CKPT), device)
    data = json.loads(DATA.read_text(encoding="utf-8"))["test"]
    game = data[REF_IDX]["game"]

    picked = [
        e for e in data
        if e["game"] == game and e["gameTime"].startswith("1 -")
        and start_s <= secs(e["gameTime"]) <= end_s
        and not (labelled_only and e["label"] == "<no_event>")
    ]
    picked.sort(key=lambda e: secs(e["gameTime"]))
    if dedupe_label:
        seen, uniq = set(), []
        for e in picked:
            if e["label"] not in seen:
                seen.add(e["label"])
                uniq.append(e)
        picked = uniq

    out = []
    for ex in picked:
        ds = CommentaryDataset([ex], vocab)
        src, _ = collate([ds[0]])
        banned = build_banned_mask([ex], vocab, device)
        ids = model.greedy_decode(src.to(device), max_len=ck["max_tgt"], banned=banned)
        tagged = vocab.decode(ids[0].tolist())
        out.append({
            "t": secs(ex["gameTime"]),
            "gameTime": ex["gameTime"],
            "label": ex["label"],
            "input": ex["input"],
            "grounding": {k: v["name"] for k, v in ex["grounding"].items()},
            "commentary": restore_names(tagged, ex["grounding"]),
        })
    return out


def draw_feed(canvas, events, now):
    """Right-hand commentary feed: entries appear at their real timestamps."""
    x0 = VID_W
    cv2.rectangle(canvas, (x0, 0), (W, H), (24, 28, 34), -1)
    cv2.line(canvas, (x0, 0), (x0, H), (60, 66, 74), 1)
    cv2.putText(canvas, "GENERATED COMMENTARY FEED", (x0 + 16, 26),
                FONT, 0.46, WHITE, 1, cv2.LINE_AA)
    cv2.putText(canvas, "custom Transformer, greedy decoding", (x0 + 16, 45),
                FONT, 0.36, GREY, 1, cv2.LINE_AA)
    cv2.line(canvas, (x0 + 16, 56), (W - 16, 56), (60, 66, 74), 1)

    shown = [e for e in events if now >= e["t"]]
    blocks = []
    for e in shown:
        body = wrap(e["commentary"], 56)
        blocks.append((e, body, 22 + 17 * len(body) + 12))

    total = sum(b[2] for b in blocks)
    avail = H - 70 - 26
    while blocks and total > avail:            # drop oldest until it fits
        total -= blocks[0][2]
        blocks.pop(0)

    y = 78
    for e, body, _h in blocks:
        goal = e["label"] == "soccer-ball"
        head = f"{e['gameTime'].replace('1 - ', '')}   {e['label']}"
        cv2.putText(canvas, head, (x0 + 16, y), FONT, 0.42,
                    GOLD if goal else AMBER, 1, cv2.LINE_AA)
        y += 20
        for ln in body:
            cv2.putText(canvas, ln, (x0 + 16, y), FONT, 0.40,
                        GREEN if goal else (200, 205, 210), 1, cv2.LINE_AA)
            y += 17
        y += 12

    if not shown:
        cv2.putText(canvas, "waiting for first annotated event ...",
                    (x0 + 16, 84), FONT, 0.40, GREY, 1, cv2.LINE_AA)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", default="highlights", choices=["highlights", "window"],
                    help="highlights: short cut around each LABELLED event "
                         "(recommended). window: one continuous span.")
    ap.add_argument("--start", type=int, default=0)
    ap.add_argument("--end", type=int, default=47 * 60)
    ap.add_argument("--pre", type=int, default=8, help="seconds before each event")
    ap.add_argument("--post", type=int, default=7, help="seconds after each event")
    ap.add_argument("--conf", type=float, default=0.30)
    ap.add_argument("--out", default=str(ROOT / "outputs" / "demo_sidebyside.mp4"))
    args = ap.parse_args()

    if not VIDEO.exists():
        sys.exit(f"missing video: {VIDEO}")

    highlights = args.mode == "highlights"
    print(f"mode: {args.mode}")
    print("generating commentary ...")
    events = generate_events(args.start, args.end,
                             labelled_only=highlights, dedupe_label=highlights)
    if not events:
        sys.exit("no annotated events in that window")
    for e in events:
        print(f"  {e['gameTime']:>9}  {e['label']:14s}  {e['commentary'][:78]}")

    from ultralytics import YOLO
    yolo = YOLO("yolov8n.pt")          # cached locally; no download

    cap = cv2.VideoCapture(str(VIDEO))
    fps = cap.get(cv2.CAP_PROP_FPS) or 25.0
    duration = cap.get(cv2.CAP_PROP_FRAME_COUNT) / fps

    # The annotation clock runs past the end of the video file: SoccerNet labels
    # this half to 46:59 but 1_224p.mkv is exactly 45:00. Events after the video
    # ends have no footage, and silently produce empty spans. Drop them loudly.
    keep = [e for e in events if e["t"] + args.post <= duration]
    dropped = [e for e in events if e not in keep]
    for e in dropped:
        print(f"  SKIP {e['gameTime']} ({e['label']}) - past end of video "
              f"({duration/60:.2f} min)")
    events = keep
    if not events:
        sys.exit("no events fall within the video duration")

    Path(args.out).parent.mkdir(exist_ok=True)
    vw = cv2.VideoWriter(args.out, cv2.VideoWriter_fourcc(*"mp4v"), fps, (W, H))
    if not vw.isOpened():
        sys.exit("could not open VideoWriter (codec problem)")

    # Build the list of (start, end) spans to play, in order.
    if highlights:
        spans = [(max(0, e["t"] - args.pre), e["t"] + args.post) for e in events]
    else:
        spans = [(args.start, args.end)]
    total_frames = sum(int((b - a) * fps) for a, b in spans)
    print(f"rendering {total_frames} frames ({W}x{H}, {len(spans)} span(s)) "
          f"-> {args.out}")

    for span_i, (span_a, span_b) in enumerate(spans):
        cap.set(cv2.CAP_PROP_POS_MSEC, span_a * 1000)
        for i in range(int((span_b - span_a) * fps)):
            ok, frame = cap.read()
            if not ok:
                break
            now = span_a + i / fps
            _render_frame(vw, yolo, frame, now, events, args.conf,
                          span_i + 1, len(spans) if highlights else 0)

    cap.release()
    vw.release()
    mb = Path(args.out).stat().st_size / 1e6
    print(f"done: {args.out}  ({mb:.1f} MB, {total_frames} frames, "
          f"{total_frames / fps:.0f}s, {len(events)} events)")


def _render_frame(vw, yolo, frame, now, events, conf, clip_no, n_clips):
        det = yolo(frame, classes=[0], conf=conf, verbose=False)[0]
        vid = cv2.resize(frame, (VID_W, VID_H), interpolation=cv2.INTER_CUBIC)
        sx, sy = VID_W / det.orig_shape[1], VID_H / det.orig_shape[0]
        for x1, y1, x2, y2 in det.boxes.xyxy.tolist():
            cv2.rectangle(vid, (int(x1 * sx), int(y1 * sy)),
                          (int(x2 * sx), int(y2 * sy)), (0, 220, 255), 1)
        cv2.putText(vid, f"YOLOv8n  players: {len(det.boxes)}", (12, 24),
                    FONT, 0.52, (0, 220, 255), 1, cv2.LINE_AA)
        mm, ss = divmod(int(now), 60)
        cv2.putText(vid, f"1st half  {mm:02d}:{ss:02d}", (VID_W - 165, 24),
                    FONT, 0.52, WHITE, 1, cv2.LINE_AA)
        if n_clips:
            cv2.putText(vid, f"clip {clip_no}/{n_clips}", (12, VID_H - 14),
                        FONT, 0.46, GREY, 1, cv2.LINE_AA)

        canvas = cv2.copyMakeBorder(vid, 0, INFO_H, 0, FEED_W,
                                    cv2.BORDER_CONSTANT, value=BG)

        cur = [e for e in events if now >= e["t"]]
        y = VID_H + 26
        if cur:
            e = cur[-1]
            cv2.putText(canvas, "ENCODER INPUT (from SoccerNet annotation)",
                        (14, y), FONT, 0.42, GREY, 1, cv2.LINE_AA)
            for ln in wrap(e["input"], 74):
                y += 18
                cv2.putText(canvas, ln, (14, y), FONT, 0.40, BLUE, 1, cv2.LINE_AA)
            y += 22
            g = ", ".join(f"{k}={v}" for k, v in e["grounding"].items()) or "(none)"
            for ln in wrap("GROUNDED: " + g, 74):
                cv2.putText(canvas, ln, (14, y), FONT, 0.40, AMBER, 1, cv2.LINE_AA)
                y += 18
        else:
            cv2.putText(canvas, "ENCODER INPUT - awaiting first event", (14, y),
                        FONT, 0.42, GREY, 1, cv2.LINE_AA)

        draw_feed(canvas, events, now)
        cv2.putText(canvas,
                    "YOLO = player detection only.  Event type + player identity "
                    "come from the annotation.  The Transformer generates the text.",
                    (14, H - 10), FONT, 0.36, GREY, 1, cv2.LINE_AA)
        vw.write(canvas)


if __name__ == "__main__":
    main()
